### ISSUE TITLE
Install of obs-worker is failing

### ISSUE THREAD

**Issue by sylvestre** [opencollab/llvm-slave-salt#2]
The obsworker task is failing because of:
```
----------
          ID: obsworker
    Function: service.running
      Result: False
     Comment: Service obsworker is already enabled, and is dead
     Started: 10:52:03.616587
    Duration: 187.339 ms
     Changes:   

```
